/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_open62541_WRAP_H_
#define SWIG_open62541_WRAP_H_

class SwigDirector_ServerAPIBase : public ServerAPIBase, public Swig::Director {

public:
    void swig_connect_director(JNIEnv *jenv, jobject jself, jclass jcls, bool swig_mem_own, bool weak_global);
    SwigDirector_ServerAPIBase(JNIEnv *jenv);
    virtual void monitored_itemChanged(UA_NodeId const *nodeId, UA_Int32 const value);
    virtual void methods_callback(UA_NodeId const *methodId, UA_NodeId const *objectId, UA_String input, UA_String output, ServerAPIBase *jAPIBase);
    virtual ~SwigDirector_ServerAPIBase();
public:
    bool swig_overrides(int n) {
      return (n < 2 ? swig_override[n] : false);
    }
protected:
    Swig::BoolArray<2> swig_override;
};

class SwigDirector_ClientAPIBase : public ClientAPIBase, public Swig::Director {

public:
    void swig_connect_director(JNIEnv *jenv, jobject jself, jclass jcls, bool swig_mem_own, bool weak_global);
    SwigDirector_ClientAPIBase(JNIEnv *jenv);
    virtual void monitored_itemChanged(UA_NodeId nodeId, UA_Int32 const value);
    virtual void client_connected(ClientAPIBase *jClientAPIBase, UA_Client *client, char *serverUrl);
    virtual void methods_callback(UA_NodeId const objectId, UA_NodeId const methodId, UA_String input, UA_String output, ClientAPIBase *jAPIBase);
    virtual ~SwigDirector_ClientAPIBase();
public:
    bool swig_overrides(int n) {
      return (n < 3 ? swig_override[n] : false);
    }
protected:
    Swig::BoolArray<3> swig_override;
};


#endif
