/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */


#ifndef SWIGJAVA
#define SWIGJAVA
#endif

#define SWIG_DIRECTORS


#ifdef __cplusplus
/* SwigValueWrapper is described in swig.swg */
template<typename T> class SwigValueWrapper {
  struct SwigMovePointer {
    T *ptr;
    SwigMovePointer(T *p) : ptr(p) { }
    ~SwigMovePointer() { delete ptr; }
    SwigMovePointer& operator=(SwigMovePointer& rhs) { T* oldptr = ptr; ptr = 0; delete oldptr; ptr = rhs.ptr; rhs.ptr = 0; return *this; }
  } pointer;
  SwigValueWrapper& operator=(const SwigValueWrapper<T>& rhs);
  SwigValueWrapper(const SwigValueWrapper<T>& rhs);
public:
  SwigValueWrapper() : pointer(0) { }
  SwigValueWrapper& operator=(const T& t) { SwigMovePointer tmp(new T(t)); pointer = tmp; return *this; }
  operator T&() const { return *pointer.ptr; }
  T *operator&() { return pointer.ptr; }
};

template <typename T> T SwigValueInit() {
  return T();
}
#endif

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if defined(__GNUC__)
#  if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#    ifndef GCC_HASCLASSVISIBILITY
#      define GCC_HASCLASSVISIBILITY
#    endif
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif


/* Fix for jlong on some versions of gcc on Windows */
#if defined(__GNUC__) && !defined(__INTEL_COMPILER)
  typedef long long __int64;
#endif

/* Fix for jlong on 64-bit x86 Solaris */
#if defined(__x86_64)
# ifdef _LP64
#   undef _LP64
# endif
#endif

#include <jni.h>
#include <stdlib.h>
#include <string.h>


/* Support for throwing Java exceptions */
typedef enum {
  SWIG_JavaOutOfMemoryError = 1, 
  SWIG_JavaIOException, 
  SWIG_JavaRuntimeException, 
  SWIG_JavaIndexOutOfBoundsException,
  SWIG_JavaArithmeticException,
  SWIG_JavaIllegalArgumentException,
  SWIG_JavaNullPointerException,
  SWIG_JavaDirectorPureVirtual,
  SWIG_JavaUnknownError
} SWIG_JavaExceptionCodes;

typedef struct {
  SWIG_JavaExceptionCodes code;
  const char *java_exception;
} SWIG_JavaExceptions_t;


static void SWIGUNUSED SWIG_JavaThrowException(JNIEnv *jenv, SWIG_JavaExceptionCodes code, const char *msg) {
  jclass excep;
  static const SWIG_JavaExceptions_t java_exceptions[] = {
    { SWIG_JavaOutOfMemoryError, "java/lang/OutOfMemoryError" },
    { SWIG_JavaIOException, "java/io/IOException" },
    { SWIG_JavaRuntimeException, "java/lang/RuntimeException" },
    { SWIG_JavaIndexOutOfBoundsException, "java/lang/IndexOutOfBoundsException" },
    { SWIG_JavaArithmeticException, "java/lang/ArithmeticException" },
    { SWIG_JavaIllegalArgumentException, "java/lang/IllegalArgumentException" },
    { SWIG_JavaNullPointerException, "java/lang/NullPointerException" },
    { SWIG_JavaDirectorPureVirtual, "java/lang/RuntimeException" },
    { SWIG_JavaUnknownError,  "java/lang/UnknownError" },
    { (SWIG_JavaExceptionCodes)0,  "java/lang/UnknownError" }
  };
  const SWIG_JavaExceptions_t *except_ptr = java_exceptions;

  while (except_ptr->code != code && except_ptr->code)
    except_ptr++;

  jenv->ExceptionClear();
  excep = jenv->FindClass(except_ptr->java_exception);
  if (excep)
    jenv->ThrowNew(excep, msg);
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_JavaThrowException(jenv, SWIG_JavaIllegalArgumentException, msg); return nullreturn; } else

/* -----------------------------------------------------------------------------
 * director_common.swg
 *
 * This file contains support for director classes which is common between
 * languages.
 * ----------------------------------------------------------------------------- */

/*
  Use -DSWIG_DIRECTOR_STATIC if you prefer to avoid the use of the
  'Swig' namespace. This could be useful for multi-modules projects.
*/
#ifdef SWIG_DIRECTOR_STATIC
/* Force anonymous (static) namespace */
#define Swig
#endif
/* -----------------------------------------------------------------------------
 * director.swg
 *
 * This file contains support for director classes so that Java proxy
 * methods can be called from C++.
 * ----------------------------------------------------------------------------- */

#if defined(DEBUG_DIRECTOR_OWNED) || defined(DEBUG_DIRECTOR_EXCEPTION) || defined(DEBUG_DIRECTOR_THREAD_NAME)
#include <iostream>
#endif

#include <exception>

#if defined(SWIG_JAVA_USE_THREAD_NAME)

#if !defined(SWIG_JAVA_GET_THREAD_NAME)
namespace Swig {
  SWIGINTERN int GetThreadName(char *name, size_t len);
}

#if defined(__linux__)

#include <sys/prctl.h>
SWIGINTERN int Swig::GetThreadName(char *name, size_t len) {
  (void)len;
#if defined(PR_GET_NAME)
  return prctl(PR_GET_NAME, (unsigned long)name, 0, 0, 0);
#else
  (void)name;
  return 1;
#endif
}

#elif defined(__unix__) || defined(__APPLE__)

#include <pthread.h>
SWIGINTERN int Swig::GetThreadName(char *name, size_t len) {
  return pthread_getname_np(pthread_self(), name, len);
}

#else

SWIGINTERN int Swig::GetThreadName(char *name, size_t len) {
  (void)len;
  (void)name;
  return 1;
}
#endif

#endif

#endif

namespace Swig {

  /* Java object wrapper */
  class JObjectWrapper {
  public:
    JObjectWrapper() : jthis_(NULL), weak_global_(true) {
    }

    ~JObjectWrapper() {
      jthis_ = NULL;
      weak_global_ = true;
    }

    bool set(JNIEnv *jenv, jobject jobj, bool mem_own, bool weak_global) {
      if (!jthis_) {
        weak_global_ = weak_global || !mem_own; // hold as weak global if explicitly requested or not owned
        if (jobj)
          jthis_ = weak_global_ ? jenv->NewWeakGlobalRef(jobj) : jenv->NewGlobalRef(jobj);
#if defined(DEBUG_DIRECTOR_OWNED)
        std::cout << "JObjectWrapper::set(" << jobj << ", " << (weak_global ? "weak_global" : "global_ref") << ") -> " << jthis_ << std::endl;
#endif
        return true;
      } else {
#if defined(DEBUG_DIRECTOR_OWNED)
        std::cout << "JObjectWrapper::set(" << jobj << ", " << (weak_global ? "weak_global" : "global_ref") << ") -> already set" << std::endl;
#endif
        return false;
      }
    }

    jobject get(JNIEnv *jenv) const {
#if defined(DEBUG_DIRECTOR_OWNED)
      std::cout << "JObjectWrapper::get(";
      if (jthis_)
        std::cout << jthis_;
      else
        std::cout << "null";
      std::cout << ") -> return new local ref" << std::endl;
#endif
      return (jthis_ ? jenv->NewLocalRef(jthis_) : jthis_);
    }

    void release(JNIEnv *jenv) {
#if defined(DEBUG_DIRECTOR_OWNED)
      std::cout << "JObjectWrapper::release(" << jthis_ << "): " << (weak_global_ ? "weak global ref" : "global ref") << std::endl;
#endif
      if (jthis_) {
        if (weak_global_) {
          if (jenv->IsSameObject(jthis_, NULL) == JNI_FALSE)
            jenv->DeleteWeakGlobalRef((jweak)jthis_);
        } else
          jenv->DeleteGlobalRef(jthis_);
      }

      jthis_ = NULL;
      weak_global_ = true;
    }

    /* Only call peek if you know what you are doing wrt to weak/global references */
    jobject peek() {
      return jthis_;
    }

    /* Java proxy releases ownership of C++ object, C++ object is now
       responsible for destruction (creates NewGlobalRef to pin Java proxy) */
    void java_change_ownership(JNIEnv *jenv, jobject jself, bool take_or_release) {
      if (take_or_release) {  /* Java takes ownership of C++ object's lifetime. */
        if (!weak_global_) {
          jenv->DeleteGlobalRef(jthis_);
          jthis_ = jenv->NewWeakGlobalRef(jself);
          weak_global_ = true;
        }
      } else {
	/* Java releases ownership of C++ object's lifetime */
        if (weak_global_) {
          jenv->DeleteWeakGlobalRef((jweak)jthis_);
          jthis_ = jenv->NewGlobalRef(jself);
          weak_global_ = false;
        }
      }
    }

  private:
    /* pointer to Java object */
    jobject jthis_;
    /* Local or global reference flag */
    bool weak_global_;
  };

  /* Local JNI reference deleter */
  class LocalRefGuard {
    JNIEnv *jenv_;
    jobject jobj_;

    // non-copyable
    LocalRefGuard(const LocalRefGuard &);
    LocalRefGuard &operator=(const LocalRefGuard &);
  public:
    LocalRefGuard(JNIEnv *jenv, jobject jobj): jenv_(jenv), jobj_(jobj) {}
    ~LocalRefGuard() {
      if (jobj_)
        jenv_->DeleteLocalRef(jobj_);
    }
  };

  /* director base class */
  class Director {
    /* pointer to Java virtual machine */
    JavaVM *swig_jvm_;

  protected:
#if defined (_MSC_VER) && (_MSC_VER<1300)
    class JNIEnvWrapper;
    friend class JNIEnvWrapper;
#endif
    /* Utility class for managing the JNI environment */
    class JNIEnvWrapper {
      const Director *director_;
      JNIEnv *jenv_;
      int env_status;
    public:
      JNIEnvWrapper(const Director *director) : director_(director), jenv_(0), env_status(0) {
#if defined(__ANDROID__)
        JNIEnv **jenv = &jenv_;
#else
        void **jenv = (void **)&jenv_;
#endif
        env_status = director_->swig_jvm_->GetEnv((void **)&jenv_, JNI_VERSION_1_2);
        JavaVMAttachArgs args;
        args.version = JNI_VERSION_1_2;
        args.group = NULL;
        args.name = NULL;
#if defined(SWIG_JAVA_USE_THREAD_NAME)
        char thread_name[64];  // MAX_TASK_COMM_LEN=16 is hard-coded in the Linux kernel and MacOS has MAXTHREADNAMESIZE=64.
        if (Swig::GetThreadName(thread_name, sizeof(thread_name)) == 0) {
          args.name = thread_name;
#if defined(DEBUG_DIRECTOR_THREAD_NAME)
          std::cout << "JNIEnvWrapper: thread name: " << thread_name << std::endl;
        } else {
          std::cout << "JNIEnvWrapper: Couldn't set Java thread name" << std::endl;
#endif
        }
#endif
#if defined(SWIG_JAVA_ATTACH_CURRENT_THREAD_AS_DAEMON)
        // Attach a daemon thread to the JVM. Useful when the JVM should not wait for
        // the thread to exit upon shutdown. Only for jdk-1.4 and later.
        director_->swig_jvm_->AttachCurrentThreadAsDaemon(jenv, &args);
#else
        director_->swig_jvm_->AttachCurrentThread(jenv, &args);
#endif
      }
      ~JNIEnvWrapper() {
#if !defined(SWIG_JAVA_NO_DETACH_CURRENT_THREAD)
        // Some JVMs, eg jdk-1.4.2 and lower on Solaris have a bug and crash with the DetachCurrentThread call.
        // However, without this call, the JVM hangs on exit when the thread was not created by the JVM and creates a memory leak.
        if (env_status == JNI_EDETACHED)
          director_->swig_jvm_->DetachCurrentThread();
#endif
      }
      JNIEnv *getJNIEnv() const {
        return jenv_;
      }
    };

    /* Java object wrapper */
    JObjectWrapper swig_self_;

    /* Disconnect director from Java object */
    void swig_disconnect_director_self(const char *disconn_method) {
      JNIEnvWrapper jnienv(this) ;
      JNIEnv *jenv = jnienv.getJNIEnv() ;
      jobject jobj = swig_self_.get(jenv);
      LocalRefGuard ref_deleter(jenv, jobj);
#if defined(DEBUG_DIRECTOR_OWNED)
      std::cout << "Swig::Director::disconnect_director_self(" << jobj << ")" << std::endl;
#endif
      if (jobj && jenv->IsSameObject(jobj, NULL) == JNI_FALSE) {
        jmethodID disconn_meth = jenv->GetMethodID(jenv->GetObjectClass(jobj), disconn_method, "()V");
        if (disconn_meth) {
#if defined(DEBUG_DIRECTOR_OWNED)
          std::cout << "Swig::Director::disconnect_director_self upcall to " << disconn_method << std::endl;
#endif
          jenv->CallVoidMethod(jobj, disconn_meth);
        }
      }
    }

  public:
    Director(JNIEnv *jenv) : swig_jvm_((JavaVM *) NULL), swig_self_() {
      /* Acquire the Java VM pointer */
      jenv->GetJavaVM(&swig_jvm_);
    }

    virtual ~Director() {
      JNIEnvWrapper jnienv(this) ;
      JNIEnv *jenv = jnienv.getJNIEnv() ;
      swig_self_.release(jenv);
    }

    bool swig_set_self(JNIEnv *jenv, jobject jself, bool mem_own, bool weak_global) {
      return swig_self_.set(jenv, jself, mem_own, weak_global);
    }

    jobject swig_get_self(JNIEnv *jenv) const {
      return swig_self_.get(jenv);
    }

    // Change C++ object's ownership, relative to Java
    void swig_java_change_ownership(JNIEnv *jenv, jobject jself, bool take_or_release) {
      swig_self_.java_change_ownership(jenv, jself, take_or_release);
    }
  };

  // Zero initialized bool array
  template<size_t N> class BoolArray {
    bool array_[N];
  public:
    BoolArray() {
      memset(array_, 0, sizeof(array_));
    }
    bool& operator[](size_t n) {
      return array_[n];
    }
    bool operator[](size_t n) const {
      return array_[n];
    }
  };

  // Utility classes and functions for exception handling.

  // Simple holder for a Java string during exception handling, providing access to a c-style string
  class JavaString {
  public:
    JavaString(JNIEnv *jenv, jstring jstr) : jenv_(jenv), jstr_(jstr), cstr_(0) {
      if (jenv_ && jstr_)
	cstr_ = (const char *) jenv_->GetStringUTFChars(jstr_, NULL);
    }

    ~JavaString() {
      if (jenv_ && jstr_ && cstr_)
	jenv_->ReleaseStringUTFChars(jstr_, cstr_);
    }

    const char *c_str(const char *null_string = "null JavaString") const {
      return cstr_ ? cstr_ : null_string;
    }

  private:
    // non-copyable
    JavaString(const JavaString &);
    JavaString &operator=(const JavaString &);

    JNIEnv *jenv_;
    jstring jstr_;
    const char *cstr_;
  };

  // Helper class to extract the exception message from a Java throwable
  class JavaExceptionMessage {
  public:
    JavaExceptionMessage(JNIEnv *jenv, jthrowable throwable) : message_(jenv, exceptionMessageFromThrowable(jenv, throwable)) {
    }

    // Return a C string of the exception message in the jthrowable passed in the constructor
    // If no message is available, null_string is return instead
    const char *message(const char *null_string = "Could not get exception message in JavaExceptionMessage") const {
      return message_.c_str(null_string);
    }

  private:
    // non-copyable
    JavaExceptionMessage(const JavaExceptionMessage &);
    JavaExceptionMessage &operator=(const JavaExceptionMessage &);

    // Get exception message by calling Java method Throwable.getMessage()
    static jstring exceptionMessageFromThrowable(JNIEnv *jenv, jthrowable throwable) {
      jstring jmsg = NULL;
      if (jenv && throwable) {
	jenv->ExceptionClear(); // Cannot invoke methods with any pending exceptions
	jclass throwclz = jenv->GetObjectClass(throwable);
	if (throwclz) {
	  // All Throwable classes have a getMessage() method, so call it to extract the exception message
	  jmethodID getMessageMethodID = jenv->GetMethodID(throwclz, "getMessage", "()Ljava/lang/String;");
	  if (getMessageMethodID)
	    jmsg = (jstring)jenv->CallObjectMethod(throwable, getMessageMethodID);
	}
	if (jmsg == NULL && jenv->ExceptionCheck())
	  jenv->ExceptionClear();
      }
      return jmsg;
    }

    JavaString message_;
  };

  // C++ Exception class for handling Java exceptions thrown during a director method Java upcall
  class DirectorException : public std::exception {
  public:

    // Construct exception from a Java throwable
    DirectorException(JNIEnv *jenv, jthrowable throwable) : jenv_(jenv), throwable_(throwable), classname_(0), msg_(0) {

      // Call Java method Object.getClass().getName() to obtain the throwable's class name (delimited by '/')
      if (jenv && throwable) {
	jenv->ExceptionClear(); // Cannot invoke methods with any pending exceptions
	jclass throwclz = jenv->GetObjectClass(throwable);
	if (throwclz) {
	  jclass clzclz = jenv->GetObjectClass(throwclz);
	  if (clzclz) {
	    jmethodID getNameMethodID = jenv->GetMethodID(clzclz, "getName", "()Ljava/lang/String;");
	    if (getNameMethodID) {
	      jstring jstr_classname = (jstring)(jenv->CallObjectMethod(throwclz, getNameMethodID));
              // Copy strings, since there is no guarantee that jenv will be active when handled
              if (jstr_classname) {
                JavaString jsclassname(jenv, jstr_classname);
                const char *classname = jsclassname.c_str(0);
                if (classname)
                  classname_ = copypath(classname);
              }
	    }
	  }
	}
      }

      JavaExceptionMessage exceptionmsg(jenv, throwable);
      msg_ = copystr(exceptionmsg.message(0));
    }

    // More general constructor for handling as a java.lang.RuntimeException
    DirectorException(const char *msg) : jenv_(0), throwable_(0), classname_(0), msg_(msg ? copystr(msg) : 0) {
    }

    ~DirectorException() throw() {
      delete[] classname_;
      delete[] msg_;
    }

    const char *what() const throw() {
      return msg_ ? msg_ : "Unspecified DirectorException message";
    }

    // Reconstruct and raise/throw the Java Exception that caused the DirectorException
    // Note that any error in the JNI exception handling results in a Java RuntimeException
    void throwException(JNIEnv *jenv) const {
      if (jenv) {
        if (jenv == jenv_ && throwable_) {
          // Throw original exception if not already pending
          jthrowable throwable = jenv->ExceptionOccurred();
          if (throwable && jenv->IsSameObject(throwable, throwable_) == JNI_FALSE) {
            jenv->ExceptionClear();
            throwable = 0;
          }
          if (!throwable)
            jenv->Throw(throwable_);
        } else {
          // Try and reconstruct original exception, but original stacktrace is not reconstructed
          jenv->ExceptionClear();

          jmethodID ctorMethodID = 0;
          jclass throwableclass = 0;
          if (classname_) {
            throwableclass = jenv->FindClass(classname_);
            if (throwableclass)
              ctorMethodID = jenv->GetMethodID(throwableclass, "<init>", "(Ljava/lang/String;)V");
          }

          if (ctorMethodID) {
            jenv->ThrowNew(throwableclass, what());
          } else {
            SWIG_JavaThrowException(jenv, SWIG_JavaRuntimeException, what());
          }
        }
      }
    }

    // Deprecated - use throwException
    void raiseJavaException(JNIEnv *jenv) const {
      throwException(jenv);
    }

    // Create and throw the DirectorException
    static void raise(JNIEnv *jenv, jthrowable throwable) {
      throw DirectorException(jenv, throwable);
    }

  private:
    static char *copypath(const char *srcmsg) {
      char *target = copystr(srcmsg);
      for (char *c=target; *c; ++c) {
        if ('.' == *c)
          *c = '/';
      }
      return target;
    }

    static char *copystr(const char *srcmsg) {
      char *target = 0;
      if (srcmsg) {
	size_t msglen = strlen(srcmsg) + 1;
	target = new char[msglen];
	strncpy(target, srcmsg, msglen);
      }
      return target;
    }

    JNIEnv *jenv_;
    jthrowable throwable_;
    const char *classname_;
    const char *msg_;
  };

  // Helper method to determine if a Java throwable matches a particular Java class type
  // Note side effect of clearing any pending exceptions
  SWIGINTERN bool ExceptionMatches(JNIEnv *jenv, jthrowable throwable, const char *classname) {
    bool matches = false;

    if (throwable && jenv && classname) {
      // Exceptions need to be cleared for correct behavior.
      // The caller of ExceptionMatches should restore pending exceptions if desired -
      // the caller already has the throwable.
      jenv->ExceptionClear();

      jclass clz = jenv->FindClass(classname);
      if (clz) {
	jclass classclz = jenv->GetObjectClass(clz);
	jmethodID isInstanceMethodID = jenv->GetMethodID(classclz, "isInstance", "(Ljava/lang/Object;)Z");
	if (isInstanceMethodID) {
	  matches = jenv->CallBooleanMethod(clz, isInstanceMethodID, throwable) != 0;
	}
      }

#if defined(DEBUG_DIRECTOR_EXCEPTION)
      if (jenv->ExceptionCheck()) {
        // Typically occurs when an invalid classname argument is passed resulting in a ClassNotFoundException
        JavaExceptionMessage exc(jenv, jenv->ExceptionOccurred());
        std::cout << "Error: ExceptionMatches: class '" << classname << "' : " << exc.message() << std::endl;
      }
#endif
    }
    return matches;
  }
}

namespace Swig {
  namespace {
    jclass jclass_open62541JNI = NULL;
    jmethodID director_method_ids[3];
  }
}

#include "open62541.h"
#include "server_api_base.h"
#include "client_api_base.h"


#include <stdint.h>		// Use the C99 official header



/* ---------------------------------------------------
 * C++ director class methods
 * --------------------------------------------------- */

#include "open62541_wrap.h"

SwigDirector_ServerAPIBase::SwigDirector_ServerAPIBase(JNIEnv *jenv) : ServerAPIBase(), Swig::Director(jenv) {
}

void SwigDirector_ServerAPIBase::monitored_itemChanged(UA_NodeId const *nodeId, UA_Int32 const value) {
  JNIEnvWrapper swigjnienv(this) ;
  JNIEnv * jenv = swigjnienv.getJNIEnv() ;
  jobject swigjobj = (jobject) NULL ;
  jlong jnodeId = 0 ;
  jint jvalue  ;
  
  if (!swig_override[0]) {
    ServerAPIBase::monitored_itemChanged(nodeId,value);
    return;
  }
  swigjobj = swig_get_self(jenv);
  if (swigjobj && jenv->IsSameObject(swigjobj, NULL) == JNI_FALSE) {
    *((UA_NodeId **)&jnodeId) = (UA_NodeId *) nodeId; 
    jvalue = (jint) value;
    jenv->CallStaticVoidMethod(Swig::jclass_open62541JNI, Swig::director_method_ids[0], swigjobj, jnodeId, jvalue);
    jthrowable swigerror = jenv->ExceptionOccurred();
    if (swigerror) {
      Swig::DirectorException::raise(jenv, swigerror);
    }
    
  } else {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null upcall object in ServerAPIBase::monitored_itemChanged ");
  }
  if (swigjobj) jenv->DeleteLocalRef(swigjobj);
}

SwigDirector_ServerAPIBase::~SwigDirector_ServerAPIBase() {
  swig_disconnect_director_self("swigDirectorDisconnect");
}


void SwigDirector_ServerAPIBase::swig_connect_director(JNIEnv *jenv, jobject jself, jclass jcls, bool swig_mem_own, bool weak_global) {
  static struct {
    const char *mname;
    const char *mdesc;
    jmethodID base_methid;
  } methods[] = {
    {
      "monitored_itemChanged", "(Lopen62Wrap/UA_NodeId;I)V", NULL 
    }
  };
  
  static jclass baseclass = 0 ;
  
  if (swig_set_self(jenv, jself, swig_mem_own, weak_global)) {
    if (!baseclass) {
      baseclass = jenv->FindClass("open62Wrap/ServerAPIBase");
      if (!baseclass) return;
      baseclass = (jclass) jenv->NewGlobalRef(baseclass);
    }
    bool derived = (jenv->IsSameObject(baseclass, jcls) ? false : true);
    for (int i = 0; i < 1; ++i) {
      if (!methods[i].base_methid) {
        methods[i].base_methid = jenv->GetMethodID(baseclass, methods[i].mname, methods[i].mdesc);
        if (!methods[i].base_methid) return;
      }
      swig_override[i] = false;
      if (derived) {
        jmethodID methid = jenv->GetMethodID(jcls, methods[i].mname, methods[i].mdesc);
        swig_override[i] = (methid != methods[i].base_methid);
        jenv->ExceptionClear();
      }
    }
  }
}


SwigDirector_ClientAPIBase::SwigDirector_ClientAPIBase(JNIEnv *jenv) : ClientAPIBase(), Swig::Director(jenv) {
}

void SwigDirector_ClientAPIBase::monitored_itemChanged(UA_NodeId nodeId, UA_Int32 const value) {
  JNIEnvWrapper swigjnienv(this) ;
  JNIEnv * jenv = swigjnienv.getJNIEnv() ;
  jobject swigjobj = (jobject) NULL ;
  jlong jnodeId  ;
  jint jvalue  ;
  
  if (!swig_override[0]) {
    ClientAPIBase::monitored_itemChanged(nodeId,value);
    return;
  }
  swigjobj = swig_get_self(jenv);
  if (swigjobj && jenv->IsSameObject(swigjobj, NULL) == JNI_FALSE) {
    jnodeId = 0;
    *((UA_NodeId **)&jnodeId) = new UA_NodeId((const UA_NodeId &)nodeId); 
    jvalue = (jint) value;
    jenv->CallStaticVoidMethod(Swig::jclass_open62541JNI, Swig::director_method_ids[1], swigjobj, jnodeId, jvalue);
    jthrowable swigerror = jenv->ExceptionOccurred();
    if (swigerror) {
      Swig::DirectorException::raise(jenv, swigerror);
    }
    
  } else {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null upcall object in ClientAPIBase::monitored_itemChanged ");
  }
  if (swigjobj) jenv->DeleteLocalRef(swigjobj);
}

void SwigDirector_ClientAPIBase::clientConnected(ClientAPIBase *jClientAPIBase, UA_Client *client, char *serverUrl) {
  JNIEnvWrapper swigjnienv(this) ;
  JNIEnv * jenv = swigjnienv.getJNIEnv() ;
  jobject swigjobj = (jobject) NULL ;
  jlong jjClientAPIBase = 0 ;
  jlong jclient = 0 ;
  jstring jserverUrl = 0 ;
  
  if (!swig_override[1]) {
    ClientAPIBase::clientConnected(jClientAPIBase,client,serverUrl);
    return;
  }
  swigjobj = swig_get_self(jenv);
  if (swigjobj && jenv->IsSameObject(swigjobj, NULL) == JNI_FALSE) {
    *((ClientAPIBase **)&jjClientAPIBase) = (ClientAPIBase *) jClientAPIBase; 
    *((UA_Client **)&jclient) = (UA_Client *) client; 
    jserverUrl = 0;
    if (serverUrl) {
      jserverUrl = jenv->NewStringUTF((const char *)serverUrl);
      if (!jserverUrl) return ;
    }
    Swig::LocalRefGuard serverUrl_refguard(jenv, jserverUrl);
    jenv->CallStaticVoidMethod(Swig::jclass_open62541JNI, Swig::director_method_ids[2], swigjobj, jjClientAPIBase, jclient, jserverUrl);
    jthrowable swigerror = jenv->ExceptionOccurred();
    if (swigerror) {
      Swig::DirectorException::raise(jenv, swigerror);
    }
    
  } else {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null upcall object in ClientAPIBase::clientConnected ");
  }
  if (swigjobj) jenv->DeleteLocalRef(swigjobj);
}

SwigDirector_ClientAPIBase::~SwigDirector_ClientAPIBase() {
  swig_disconnect_director_self("swigDirectorDisconnect");
}


void SwigDirector_ClientAPIBase::swig_connect_director(JNIEnv *jenv, jobject jself, jclass jcls, bool swig_mem_own, bool weak_global) {
  static struct {
    const char *mname;
    const char *mdesc;
    jmethodID base_methid;
  } methods[] = {
    {
      "monitored_itemChanged", "(Lopen62Wrap/UA_NodeId;I)V", NULL 
    },
    {
      "clientConnected", "(Lopen62Wrap/ClientAPIBase;Lopen62Wrap/SWIGTYPE_p_UA_Client;Ljava/lang/String;)V", NULL 
    }
  };
  
  static jclass baseclass = 0 ;
  
  if (swig_set_self(jenv, jself, swig_mem_own, weak_global)) {
    if (!baseclass) {
      baseclass = jenv->FindClass("open62Wrap/ClientAPIBase");
      if (!baseclass) return;
      baseclass = (jclass) jenv->NewGlobalRef(baseclass);
    }
    bool derived = (jenv->IsSameObject(baseclass, jcls) ? false : true);
    for (int i = 0; i < 2; ++i) {
      if (!methods[i].base_methid) {
        methods[i].base_methid = jenv->GetMethodID(baseclass, methods[i].mname, methods[i].mdesc);
        if (!methods[i].base_methid) return;
      }
      swig_override[i] = false;
      if (derived) {
        jmethodID methid = jenv->GetMethodID(jcls, methods[i].mname, methods[i].mdesc);
        swig_override[i] = (methid != methods[i].base_methid);
        jenv->ExceptionClear();
      }
    }
  }
}



#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT jlong JNICALL Java_open62Wrap_open62541JNI_ServerAPIBase_1Get(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  ServerAPIBase *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (ServerAPIBase *)ServerAPIBase::Get();
  *(ServerAPIBase **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_open62Wrap_open62541JNI_ServerAPIBase_1stopHandler(JNIEnv *jenv, jclass jcls, jint jarg1) {
  int arg1 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  ServerAPIBase::stopHandler(arg1);
}


SWIGEXPORT jlong JNICALL Java_open62Wrap_open62541JNI_ServerAPIBase_1createServerDefaultConfig(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  ServerAPIBase *arg1 = (ServerAPIBase *) 0 ;
  UA_Server *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(ServerAPIBase **)&jarg1; 
  result = (UA_Server *)(arg1)->createServerDefaultConfig();
  *(UA_Server **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_open62Wrap_open62541JNI_ServerAPIBase_1createServer(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2, jstring jarg3) {
  jlong jresult = 0 ;
  ServerAPIBase *arg1 = (ServerAPIBase *) 0 ;
  UA_UInt16 arg2 ;
  char *arg3 = (char *) 0 ;
  UA_Server *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(ServerAPIBase **)&jarg1; 
  arg2 = (UA_UInt16)jarg2; 
  arg3 = 0;
  if (jarg3) {
    arg3 = (char *)jenv->GetStringUTFChars(jarg3, 0);
    if (!arg3) return 0;
  }
  result = (UA_Server *)(arg1)->createServer(arg2,arg3);
  *(UA_Server **)&jresult = result; 
  if (arg3) jenv->ReleaseStringUTFChars(jarg3, (const char *)arg3);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_open62Wrap_open62541JNI_ServerAPIBase_1runServer(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  jlong jresult = 0 ;
  ServerAPIBase *arg1 = (ServerAPIBase *) 0 ;
  UA_Server *arg2 = (UA_Server *) 0 ;
  UA_Server *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(ServerAPIBase **)&jarg1; 
  arg2 = *(UA_Server **)&jarg2; 
  result = (UA_Server *)(arg1)->runServer(arg2);
  *(UA_Server **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_open62Wrap_open62541JNI_ServerAPIBase_1addMonitoredItem(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_, jlong jarg3, jlong jarg4, jobject jarg4_) {
  ServerAPIBase *arg1 = (ServerAPIBase *) 0 ;
  ServerAPIBase *arg2 = (ServerAPIBase *) 0 ;
  UA_Server *arg3 = (UA_Server *) 0 ;
  UA_NodeId arg4 ;
  UA_NodeId *argp4 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  (void)jarg4_;
  arg1 = *(ServerAPIBase **)&jarg1; 
  arg2 = *(ServerAPIBase **)&jarg2; 
  arg3 = *(UA_Server **)&jarg3; 
  argp4 = *(UA_NodeId **)&jarg4; 
  if (!argp4) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null UA_NodeId");
    return ;
  }
  arg4 = *argp4; 
  (arg1)->addMonitoredItem(arg2,arg3,arg4);
}


SWIGEXPORT jlong JNICALL Java_open62Wrap_open62541JNI_ServerAPIBase_1manuallyDefineIMM(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  jlong jresult = 0 ;
  ServerAPIBase *arg1 = (ServerAPIBase *) 0 ;
  UA_Server *arg2 = (UA_Server *) 0 ;
  UA_NodeId result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(ServerAPIBase **)&jarg1; 
  arg2 = *(UA_Server **)&jarg2; 
  result = (arg1)->manuallyDefineIMM(arg2);
  *(UA_NodeId **)&jresult = new UA_NodeId((const UA_NodeId &)result); 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_open62Wrap_open62541JNI_ServerAPIBase_1manuallyDefineRobot(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  jlong jresult = 0 ;
  ServerAPIBase *arg1 = (ServerAPIBase *) 0 ;
  UA_Server *arg2 = (UA_Server *) 0 ;
  UA_NodeId result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(ServerAPIBase **)&jarg1; 
  arg2 = *(UA_Server **)&jarg2; 
  result = (arg1)->manuallyDefineRobot(arg2);
  *(UA_NodeId **)&jresult = new UA_NodeId((const UA_NodeId &)result); 
  return jresult;
}


SWIGEXPORT void JNICALL Java_open62Wrap_open62541JNI_ServerAPIBase_1writeVariable(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jlong jarg3, jobject jarg3_, jint jarg4) {
  ServerAPIBase *arg1 = (ServerAPIBase *) 0 ;
  UA_Server *arg2 = (UA_Server *) 0 ;
  UA_NodeId *arg3 = (UA_NodeId *) 0 ;
  UA_Int32 arg4 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg3_;
  arg1 = *(ServerAPIBase **)&jarg1; 
  arg2 = *(UA_Server **)&jarg2; 
  arg3 = *(UA_NodeId **)&jarg3; 
  arg4 = (UA_Int32)jarg4; 
  (arg1)->writeVariable(arg2,arg3,arg4);
}


SWIGEXPORT void JNICALL Java_open62Wrap_open62541JNI_ServerAPIBase_1monitored_1itemChanged(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_, jint jarg3) {
  ServerAPIBase *arg1 = (ServerAPIBase *) 0 ;
  UA_NodeId *arg2 = (UA_NodeId *) 0 ;
  UA_Int32 arg3 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(ServerAPIBase **)&jarg1; 
  arg2 = *(UA_NodeId **)&jarg2; 
  arg3 = (UA_Int32)jarg3; 
  (arg1)->monitored_itemChanged((UA_NodeId const *)arg2,arg3);
}


SWIGEXPORT void JNICALL Java_open62Wrap_open62541JNI_ServerAPIBase_1monitored_1itemChangedSwigExplicitServerAPIBase(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_, jint jarg3) {
  ServerAPIBase *arg1 = (ServerAPIBase *) 0 ;
  UA_NodeId *arg2 = (UA_NodeId *) 0 ;
  UA_Int32 arg3 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(ServerAPIBase **)&jarg1; 
  arg2 = *(UA_NodeId **)&jarg2; 
  arg3 = (UA_Int32)jarg3; 
  (arg1)->ServerAPIBase::monitored_itemChanged((UA_NodeId const *)arg2,arg3);
}


SWIGEXPORT void JNICALL Java_open62Wrap_open62541JNI_delete_1ServerAPIBase(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  ServerAPIBase *arg1 = (ServerAPIBase *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(ServerAPIBase **)&jarg1; 
  delete arg1;
}


SWIGEXPORT jlong JNICALL Java_open62Wrap_open62541JNI_new_1ServerAPIBase(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  ServerAPIBase *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (ServerAPIBase *)new SwigDirector_ServerAPIBase(jenv);
  *(ServerAPIBase **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_open62Wrap_open62541JNI_ServerAPIBase_1director_1connect(JNIEnv *jenv, jclass jcls, jobject jself, jlong objarg, jboolean jswig_mem_own, jboolean jweak_global) {
  ServerAPIBase *obj = *((ServerAPIBase **)&objarg);
  (void)jcls;
  SwigDirector_ServerAPIBase *director = static_cast<SwigDirector_ServerAPIBase *>(obj);
  director->swig_connect_director(jenv, jself, jenv->GetObjectClass(jself), (jswig_mem_own == JNI_TRUE), (jweak_global == JNI_TRUE));
}


SWIGEXPORT void JNICALL Java_open62Wrap_open62541JNI_ServerAPIBase_1change_1ownership(JNIEnv *jenv, jclass jcls, jobject jself, jlong objarg, jboolean jtake_or_release) {
  ServerAPIBase *obj = *((ServerAPIBase **)&objarg);
  SwigDirector_ServerAPIBase *director = dynamic_cast<SwigDirector_ServerAPIBase *>(obj);
  (void)jcls;
  if (director) {
    director->swig_java_change_ownership(jenv, jself, jtake_or_release ? true : false);
  }
}


SWIGEXPORT void JNICALL Java_open62Wrap_open62541JNI_ClientAPIBase_1current_1nodeId_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  ClientAPIBase *arg1 = (ClientAPIBase *) 0 ;
  UA_NodeId *arg2 = (UA_NodeId *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(ClientAPIBase **)&jarg1; 
  arg2 = *(UA_NodeId **)&jarg2; 
  if (arg1) (arg1)->current_nodeId = *arg2;
}


SWIGEXPORT jlong JNICALL Java_open62Wrap_open62541JNI_ClientAPIBase_1current_1nodeId_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  ClientAPIBase *arg1 = (ClientAPIBase *) 0 ;
  UA_NodeId *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(ClientAPIBase **)&jarg1; 
  result = (UA_NodeId *)& ((arg1)->current_nodeId);
  *(UA_NodeId **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_open62Wrap_open62541JNI_ClientAPIBase_1running_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jboolean jarg2) {
  ClientAPIBase *arg1 = (ClientAPIBase *) 0 ;
  UA_Boolean arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(ClientAPIBase **)&jarg1; 
  arg2 = jarg2 ? true : false; 
  if (arg1) (arg1)->running = arg2;
}


SWIGEXPORT jboolean JNICALL Java_open62Wrap_open62541JNI_ClientAPIBase_1running_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jboolean jresult = 0 ;
  ClientAPIBase *arg1 = (ClientAPIBase *) 0 ;
  UA_Boolean result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(ClientAPIBase **)&jarg1; 
  result = (UA_Boolean) ((arg1)->running);
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_open62Wrap_open62541JNI_ClientAPIBase_1Get(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  ClientAPIBase *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (ClientAPIBase *)ClientAPIBase::Get();
  *(ClientAPIBase **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_open62Wrap_open62541JNI_ClientAPIBase_1stopHandler(JNIEnv *jenv, jclass jcls, jint jarg1) {
  int arg1 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  ClientAPIBase::stopHandler(arg1);
}


SWIGEXPORT void JNICALL Java_open62Wrap_open62541JNI_ClientAPIBase_1inactivityCallback(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  UA_Client *arg1 = (UA_Client *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(UA_Client **)&jarg1; 
  ClientAPIBase::inactivityCallback(arg1);
}


SWIGEXPORT jlong JNICALL Java_open62Wrap_open62541JNI_ClientAPIBase_1initClient(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  UA_Client *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (UA_Client *)ClientAPIBase::initClient();
  *(UA_Client **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_open62Wrap_open62541JNI_ClientAPIBase_1clientConnect(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jstring jarg3) {
  jint jresult = 0 ;
  ClientAPIBase *arg1 = (ClientAPIBase *) 0 ;
  UA_Client *arg2 = (UA_Client *) 0 ;
  char *arg3 = (char *) 0 ;
  UA_StatusCode result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(ClientAPIBase **)&jarg1; 
  arg2 = *(UA_Client **)&jarg2; 
  arg3 = 0;
  if (jarg3) {
    arg3 = (char *)jenv->GetStringUTFChars(jarg3, 0);
    if (!arg3) return 0;
  }
  result = (UA_StatusCode)ClientAPIBase::clientConnect(arg1,arg2,arg3);
  jresult = (jint)result; 
  if (arg3) jenv->ReleaseStringUTFChars(jarg3, (const char *)arg3);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_open62Wrap_open62541JNI_ClientAPIBase_1nodeIter(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jstring jarg3) {
  jlong jresult = 0 ;
  UA_NodeId arg1 ;
  UA_Client *arg2 = (UA_Client *) 0 ;
  char *arg3 = (char *) 0 ;
  UA_NodeId *argp1 ;
  UA_NodeId result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  argp1 = *(UA_NodeId **)&jarg1; 
  if (!argp1) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null UA_NodeId");
    return 0;
  }
  arg1 = *argp1; 
  arg2 = *(UA_Client **)&jarg2; 
  arg3 = 0;
  if (jarg3) {
    arg3 = (char *)jenv->GetStringUTFChars(jarg3, 0);
    if (!arg3) return 0;
  }
  result = ClientAPIBase::nodeIter(arg1,arg2,arg3);
  *(UA_NodeId **)&jresult = new UA_NodeId((const UA_NodeId &)result); 
  if (arg3) jenv->ReleaseStringUTFChars(jarg3, (const char *)arg3);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_open62Wrap_open62541JNI_ClientAPIBase_1getNodeByName(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2) {
  jlong jresult = 0 ;
  UA_Client *arg1 = (UA_Client *) 0 ;
  char *arg2 = (char *) 0 ;
  UA_NodeId result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(UA_Client **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)jenv->GetStringUTFChars(jarg2, 0);
    if (!arg2) return 0;
  }
  result = ClientAPIBase::getNodeByName(arg1,arg2);
  *(UA_NodeId **)&jresult = new UA_NodeId((const UA_NodeId &)result); 
  if (arg2) jenv->ReleaseStringUTFChars(jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_open62Wrap_open62541JNI_ClientAPIBase_1clientSubtoNode(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jlong jarg3, jobject jarg3_) {
  jint jresult = 0 ;
  ClientAPIBase *arg1 = (ClientAPIBase *) 0 ;
  UA_Client *arg2 = (UA_Client *) 0 ;
  UA_NodeId arg3 ;
  UA_NodeId *argp3 ;
  UA_UInt32 result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg3_;
  arg1 = *(ClientAPIBase **)&jarg1; 
  arg2 = *(UA_Client **)&jarg2; 
  argp3 = *(UA_NodeId **)&jarg3; 
  if (!argp3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null UA_NodeId");
    return 0;
  }
  arg3 = *argp3; 
  result = (UA_UInt32)ClientAPIBase::clientSubtoNode(arg1,arg2,arg3);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_open62Wrap_open62541JNI_ClientAPIBase_1clientRemoveSub(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2) {
  UA_Client *arg1 = (UA_Client *) 0 ;
  UA_UInt32 arg2 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(UA_Client **)&jarg1; 
  arg2 = (UA_UInt32)jarg2; 
  ClientAPIBase::clientRemoveSub(arg1,arg2);
}


SWIGEXPORT jint JNICALL Java_open62Wrap_open62541JNI_ClientAPIBase_1clientReadValue(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jobject jarg2_) {
  jint jresult = 0 ;
  UA_Client *arg1 = (UA_Client *) 0 ;
  UA_NodeId arg2 ;
  UA_NodeId *argp2 ;
  UA_Int32 result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg2_;
  arg1 = *(UA_Client **)&jarg1; 
  argp2 = *(UA_NodeId **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null UA_NodeId");
    return 0;
  }
  arg2 = *argp2; 
  result = (UA_Int32)ClientAPIBase::clientReadValue(arg1,arg2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_open62Wrap_open62541JNI_ClientAPIBase_1clientWriteValue(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jobject jarg2_, jint jarg3) {
  jint jresult = 0 ;
  UA_Client *arg1 = (UA_Client *) 0 ;
  UA_NodeId arg2 ;
  UA_Int32 arg3 ;
  UA_NodeId *argp2 ;
  UA_StatusCode result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg2_;
  arg1 = *(UA_Client **)&jarg1; 
  argp2 = *(UA_NodeId **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null UA_NodeId");
    return 0;
  }
  arg2 = *argp2; 
  arg3 = (UA_Int32)jarg3; 
  result = (UA_StatusCode)ClientAPIBase::clientWriteValue(arg1,arg2,arg3);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_open62Wrap_open62541JNI_ClientAPIBase_1deleteSubscriptionCallback(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jlong jarg3) {
  UA_Client *arg1 = (UA_Client *) 0 ;
  UA_UInt32 arg2 ;
  void *arg3 = (void *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(UA_Client **)&jarg1; 
  arg2 = (UA_UInt32)jarg2; 
  arg3 = *(void **)&jarg3; 
  ClientAPIBase::deleteSubscriptionCallback(arg1,arg2,arg3);
}


SWIGEXPORT void JNICALL Java_open62Wrap_open62541JNI_ClientAPIBase_1subscriptionInactivityCallback(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jlong jarg3) {
  UA_Client *arg1 = (UA_Client *) 0 ;
  UA_UInt32 arg2 ;
  void *arg3 = (void *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(UA_Client **)&jarg1; 
  arg2 = (UA_UInt32)jarg2; 
  arg3 = *(void **)&jarg3; 
  ClientAPIBase::subscriptionInactivityCallback(arg1,arg2,arg3);
}


SWIGEXPORT void JNICALL Java_open62Wrap_open62541JNI_ClientAPIBase_1monitored_1itemChanged(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_, jint jarg3) {
  ClientAPIBase *arg1 = (ClientAPIBase *) 0 ;
  UA_NodeId arg2 ;
  UA_Int32 arg3 ;
  UA_NodeId *argp2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(ClientAPIBase **)&jarg1; 
  argp2 = *(UA_NodeId **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null UA_NodeId");
    return ;
  }
  arg2 = *argp2; 
  arg3 = (UA_Int32)jarg3; 
  (arg1)->monitored_itemChanged(arg2,arg3);
}


SWIGEXPORT void JNICALL Java_open62Wrap_open62541JNI_ClientAPIBase_1monitored_1itemChangedSwigExplicitClientAPIBase(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_, jint jarg3) {
  ClientAPIBase *arg1 = (ClientAPIBase *) 0 ;
  UA_NodeId arg2 ;
  UA_Int32 arg3 ;
  UA_NodeId *argp2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(ClientAPIBase **)&jarg1; 
  argp2 = *(UA_NodeId **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null UA_NodeId");
    return ;
  }
  arg2 = *argp2; 
  arg3 = (UA_Int32)jarg3; 
  (arg1)->ClientAPIBase::monitored_itemChanged(arg2,arg3);
}


SWIGEXPORT void JNICALL Java_open62Wrap_open62541JNI_ClientAPIBase_1clientConnected(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_, jlong jarg3, jstring jarg4) {
  ClientAPIBase *arg1 = (ClientAPIBase *) 0 ;
  ClientAPIBase *arg2 = (ClientAPIBase *) 0 ;
  UA_Client *arg3 = (UA_Client *) 0 ;
  char *arg4 = (char *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(ClientAPIBase **)&jarg1; 
  arg2 = *(ClientAPIBase **)&jarg2; 
  arg3 = *(UA_Client **)&jarg3; 
  arg4 = 0;
  if (jarg4) {
    arg4 = (char *)jenv->GetStringUTFChars(jarg4, 0);
    if (!arg4) return ;
  }
  (arg1)->clientConnected(arg2,arg3,arg4);
  if (arg4) jenv->ReleaseStringUTFChars(jarg4, (const char *)arg4);
}


SWIGEXPORT void JNICALL Java_open62Wrap_open62541JNI_ClientAPIBase_1clientConnectedSwigExplicitClientAPIBase(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_, jlong jarg3, jstring jarg4) {
  ClientAPIBase *arg1 = (ClientAPIBase *) 0 ;
  ClientAPIBase *arg2 = (ClientAPIBase *) 0 ;
  UA_Client *arg3 = (UA_Client *) 0 ;
  char *arg4 = (char *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(ClientAPIBase **)&jarg1; 
  arg2 = *(ClientAPIBase **)&jarg2; 
  arg3 = *(UA_Client **)&jarg3; 
  arg4 = 0;
  if (jarg4) {
    arg4 = (char *)jenv->GetStringUTFChars(jarg4, 0);
    if (!arg4) return ;
  }
  (arg1)->ClientAPIBase::clientConnected(arg2,arg3,arg4);
  if (arg4) jenv->ReleaseStringUTFChars(jarg4, (const char *)arg4);
}


SWIGEXPORT void JNICALL Java_open62Wrap_open62541JNI_delete_1ClientAPIBase(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  ClientAPIBase *arg1 = (ClientAPIBase *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(ClientAPIBase **)&jarg1; 
  delete arg1;
}


SWIGEXPORT jlong JNICALL Java_open62Wrap_open62541JNI_new_1ClientAPIBase(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  ClientAPIBase *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (ClientAPIBase *)new SwigDirector_ClientAPIBase(jenv);
  *(ClientAPIBase **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_open62Wrap_open62541JNI_ClientAPIBase_1director_1connect(JNIEnv *jenv, jclass jcls, jobject jself, jlong objarg, jboolean jswig_mem_own, jboolean jweak_global) {
  ClientAPIBase *obj = *((ClientAPIBase **)&objarg);
  (void)jcls;
  SwigDirector_ClientAPIBase *director = static_cast<SwigDirector_ClientAPIBase *>(obj);
  director->swig_connect_director(jenv, jself, jenv->GetObjectClass(jself), (jswig_mem_own == JNI_TRUE), (jweak_global == JNI_TRUE));
}


SWIGEXPORT void JNICALL Java_open62Wrap_open62541JNI_ClientAPIBase_1change_1ownership(JNIEnv *jenv, jclass jcls, jobject jself, jlong objarg, jboolean jtake_or_release) {
  ClientAPIBase *obj = *((ClientAPIBase **)&objarg);
  SwigDirector_ClientAPIBase *director = dynamic_cast<SwigDirector_ClientAPIBase *>(obj);
  (void)jcls;
  if (director) {
    director->swig_java_change_ownership(jenv, jself, jtake_or_release ? true : false);
  }
}


SWIGEXPORT jint JNICALL Java_open62Wrap_open62541JNI_UA_1NODEIDTYPE_1NUMERIC_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  UA_NodeIdType result;
  
  (void)jenv;
  (void)jcls;
  result = (UA_NodeIdType)UA_NODEIDTYPE_NUMERIC;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_open62Wrap_open62541JNI_UA_1NODEIDTYPE_1STRING_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  UA_NodeIdType result;
  
  (void)jenv;
  (void)jcls;
  result = (UA_NodeIdType)UA_NODEIDTYPE_STRING;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_open62Wrap_open62541JNI_UA_1NODEIDTYPE_1GUID_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  UA_NodeIdType result;
  
  (void)jenv;
  (void)jcls;
  result = (UA_NodeIdType)UA_NODEIDTYPE_GUID;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_open62Wrap_open62541JNI_UA_1NODEIDTYPE_1BYTESTRING_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  UA_NodeIdType result;
  
  (void)jenv;
  (void)jcls;
  result = (UA_NodeIdType)UA_NODEIDTYPE_BYTESTRING;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_open62Wrap_open62541JNI_UA_1NodeId_1namespaceIndex_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  UA_NodeId *arg1 = (UA_NodeId *) 0 ;
  UA_UInt16 arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(UA_NodeId **)&jarg1; 
  arg2 = (UA_UInt16)jarg2; 
  if (arg1) (arg1)->namespaceIndex = arg2;
}


SWIGEXPORT jint JNICALL Java_open62Wrap_open62541JNI_UA_1NodeId_1namespaceIndex_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  UA_NodeId *arg1 = (UA_NodeId *) 0 ;
  UA_UInt16 result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(UA_NodeId **)&jarg1; 
  result = (UA_UInt16) ((arg1)->namespaceIndex);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_open62Wrap_open62541JNI_UA_1NodeId_1identifierType_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  UA_NodeId *arg1 = (UA_NodeId *) 0 ;
  enum UA_NodeIdType arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(UA_NodeId **)&jarg1; 
  arg2 = (enum UA_NodeIdType)jarg2; 
  if (arg1) (arg1)->identifierType = arg2;
}


SWIGEXPORT jint JNICALL Java_open62Wrap_open62541JNI_UA_1NodeId_1identifierType_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  UA_NodeId *arg1 = (UA_NodeId *) 0 ;
  enum UA_NodeIdType result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(UA_NodeId **)&jarg1; 
  result = (enum UA_NodeIdType) ((arg1)->identifierType);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_open62Wrap_open62541JNI_new_1UA_1NodeId(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  UA_NodeId *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (UA_NodeId *)new UA_NodeId();
  *(UA_NodeId **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_open62Wrap_open62541JNI_delete_1UA_1NodeId(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  UA_NodeId *arg1 = (UA_NodeId *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(UA_NodeId **)&jarg1; 
  delete arg1;
}


SWIGEXPORT void JNICALL Java_open62Wrap_open62541JNI_UA_1String_1length_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  UA_String *arg1 = (UA_String *) 0 ;
  size_t arg2 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(UA_String **)&jarg1; 
  arg2 = (size_t)jarg2; 
  if (arg1) (arg1)->length = arg2;
}


SWIGEXPORT jlong JNICALL Java_open62Wrap_open62541JNI_UA_1String_1length_1get(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  UA_String *arg1 = (UA_String *) 0 ;
  size_t result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(UA_String **)&jarg1; 
  result =  ((arg1)->length);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_open62Wrap_open62541JNI_UA_1String_1data_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  UA_String *arg1 = (UA_String *) 0 ;
  UA_Byte *arg2 = (UA_Byte *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(UA_String **)&jarg1; 
  arg2 = *(UA_Byte **)&jarg2; 
  if (arg1) (arg1)->data = arg2;
}


SWIGEXPORT jlong JNICALL Java_open62Wrap_open62541JNI_UA_1String_1data_1get(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  UA_String *arg1 = (UA_String *) 0 ;
  UA_Byte *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(UA_String **)&jarg1; 
  result = (UA_Byte *) ((arg1)->data);
  *(UA_Byte **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_open62Wrap_open62541JNI_new_1UA_1String(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  UA_String *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (UA_String *)new UA_String();
  *(UA_String **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_open62Wrap_open62541JNI_delete_1UA_1String(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  UA_String *arg1 = (UA_String *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(UA_String **)&jarg1; 
  delete arg1;
}


SWIGEXPORT void JNICALL Java_open62Wrap_open62541JNI_UA_1DataValue_1value_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  UA_DataValue *arg1 = (UA_DataValue *) 0 ;
  UA_Variant arg2 ;
  UA_Variant *argp2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(UA_DataValue **)&jarg1; 
  argp2 = *(UA_Variant **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null UA_Variant");
    return ;
  }
  arg2 = *argp2; 
  if (arg1) (arg1)->value = arg2;
}


SWIGEXPORT jlong JNICALL Java_open62Wrap_open62541JNI_UA_1DataValue_1value_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  UA_DataValue *arg1 = (UA_DataValue *) 0 ;
  UA_Variant result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(UA_DataValue **)&jarg1; 
  result =  ((arg1)->value);
  *(UA_Variant **)&jresult = new UA_Variant((const UA_Variant &)result); 
  return jresult;
}


SWIGEXPORT void JNICALL Java_open62Wrap_open62541JNI_UA_1DataValue_1sourceTimestamp_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  UA_DataValue *arg1 = (UA_DataValue *) 0 ;
  UA_DateTime arg2 ;
  UA_DateTime *argp2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(UA_DataValue **)&jarg1; 
  argp2 = *(UA_DateTime **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null UA_DateTime");
    return ;
  }
  arg2 = *argp2; 
  if (arg1) (arg1)->sourceTimestamp = arg2;
}


SWIGEXPORT jlong JNICALL Java_open62Wrap_open62541JNI_UA_1DataValue_1sourceTimestamp_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  UA_DataValue *arg1 = (UA_DataValue *) 0 ;
  UA_DateTime result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(UA_DataValue **)&jarg1; 
  result =  ((arg1)->sourceTimestamp);
  *(UA_DateTime **)&jresult = new UA_DateTime((const UA_DateTime &)result); 
  return jresult;
}


SWIGEXPORT void JNICALL Java_open62Wrap_open62541JNI_UA_1DataValue_1serverTimestamp_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  UA_DataValue *arg1 = (UA_DataValue *) 0 ;
  UA_DateTime arg2 ;
  UA_DateTime *argp2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(UA_DataValue **)&jarg1; 
  argp2 = *(UA_DateTime **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null UA_DateTime");
    return ;
  }
  arg2 = *argp2; 
  if (arg1) (arg1)->serverTimestamp = arg2;
}


SWIGEXPORT jlong JNICALL Java_open62Wrap_open62541JNI_UA_1DataValue_1serverTimestamp_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  UA_DataValue *arg1 = (UA_DataValue *) 0 ;
  UA_DateTime result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(UA_DataValue **)&jarg1; 
  result =  ((arg1)->serverTimestamp);
  *(UA_DateTime **)&jresult = new UA_DateTime((const UA_DateTime &)result); 
  return jresult;
}


SWIGEXPORT void JNICALL Java_open62Wrap_open62541JNI_UA_1DataValue_1sourcePicoseconds_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  UA_DataValue *arg1 = (UA_DataValue *) 0 ;
  UA_UInt16 arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(UA_DataValue **)&jarg1; 
  arg2 = (UA_UInt16)jarg2; 
  if (arg1) (arg1)->sourcePicoseconds = arg2;
}


SWIGEXPORT jint JNICALL Java_open62Wrap_open62541JNI_UA_1DataValue_1sourcePicoseconds_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  UA_DataValue *arg1 = (UA_DataValue *) 0 ;
  UA_UInt16 result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(UA_DataValue **)&jarg1; 
  result = (UA_UInt16) ((arg1)->sourcePicoseconds);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_open62Wrap_open62541JNI_UA_1DataValue_1serverPicoseconds_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  UA_DataValue *arg1 = (UA_DataValue *) 0 ;
  UA_UInt16 arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(UA_DataValue **)&jarg1; 
  arg2 = (UA_UInt16)jarg2; 
  if (arg1) (arg1)->serverPicoseconds = arg2;
}


SWIGEXPORT jint JNICALL Java_open62Wrap_open62541JNI_UA_1DataValue_1serverPicoseconds_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  UA_DataValue *arg1 = (UA_DataValue *) 0 ;
  UA_UInt16 result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(UA_DataValue **)&jarg1; 
  result = (UA_UInt16) ((arg1)->serverPicoseconds);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_open62Wrap_open62541JNI_UA_1DataValue_1status_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  UA_DataValue *arg1 = (UA_DataValue *) 0 ;
  UA_StatusCode arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(UA_DataValue **)&jarg1; 
  arg2 = (UA_StatusCode)jarg2; 
  if (arg1) (arg1)->status = arg2;
}


SWIGEXPORT jint JNICALL Java_open62Wrap_open62541JNI_UA_1DataValue_1status_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  UA_DataValue *arg1 = (UA_DataValue *) 0 ;
  UA_StatusCode result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(UA_DataValue **)&jarg1; 
  result = (UA_StatusCode) ((arg1)->status);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_open62Wrap_open62541JNI_UA_1DataValue_1hasValue_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jboolean jarg2) {
  UA_DataValue *arg1 = (UA_DataValue *) 0 ;
  UA_Boolean arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(UA_DataValue **)&jarg1; 
  arg2 = jarg2 ? true : false; 
  if (arg1) (arg1)->hasValue = arg2;
}


SWIGEXPORT jboolean JNICALL Java_open62Wrap_open62541JNI_UA_1DataValue_1hasValue_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jboolean jresult = 0 ;
  UA_DataValue *arg1 = (UA_DataValue *) 0 ;
  UA_Boolean result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(UA_DataValue **)&jarg1; 
  result = (UA_Boolean) ((arg1)->hasValue);
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_open62Wrap_open62541JNI_UA_1DataValue_1hasStatus_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jboolean jarg2) {
  UA_DataValue *arg1 = (UA_DataValue *) 0 ;
  UA_Boolean arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(UA_DataValue **)&jarg1; 
  arg2 = jarg2 ? true : false; 
  if (arg1) (arg1)->hasStatus = arg2;
}


SWIGEXPORT jboolean JNICALL Java_open62Wrap_open62541JNI_UA_1DataValue_1hasStatus_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jboolean jresult = 0 ;
  UA_DataValue *arg1 = (UA_DataValue *) 0 ;
  UA_Boolean result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(UA_DataValue **)&jarg1; 
  result = (UA_Boolean) ((arg1)->hasStatus);
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_open62Wrap_open62541JNI_UA_1DataValue_1hasSourceTimestamp_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jboolean jarg2) {
  UA_DataValue *arg1 = (UA_DataValue *) 0 ;
  UA_Boolean arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(UA_DataValue **)&jarg1; 
  arg2 = jarg2 ? true : false; 
  if (arg1) (arg1)->hasSourceTimestamp = arg2;
}


SWIGEXPORT jboolean JNICALL Java_open62Wrap_open62541JNI_UA_1DataValue_1hasSourceTimestamp_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jboolean jresult = 0 ;
  UA_DataValue *arg1 = (UA_DataValue *) 0 ;
  UA_Boolean result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(UA_DataValue **)&jarg1; 
  result = (UA_Boolean) ((arg1)->hasSourceTimestamp);
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_open62Wrap_open62541JNI_UA_1DataValue_1hasServerTimestamp_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jboolean jarg2) {
  UA_DataValue *arg1 = (UA_DataValue *) 0 ;
  UA_Boolean arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(UA_DataValue **)&jarg1; 
  arg2 = jarg2 ? true : false; 
  if (arg1) (arg1)->hasServerTimestamp = arg2;
}


SWIGEXPORT jboolean JNICALL Java_open62Wrap_open62541JNI_UA_1DataValue_1hasServerTimestamp_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jboolean jresult = 0 ;
  UA_DataValue *arg1 = (UA_DataValue *) 0 ;
  UA_Boolean result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(UA_DataValue **)&jarg1; 
  result = (UA_Boolean) ((arg1)->hasServerTimestamp);
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_open62Wrap_open62541JNI_UA_1DataValue_1hasSourcePicoseconds_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jboolean jarg2) {
  UA_DataValue *arg1 = (UA_DataValue *) 0 ;
  UA_Boolean arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(UA_DataValue **)&jarg1; 
  arg2 = jarg2 ? true : false; 
  if (arg1) (arg1)->hasSourcePicoseconds = arg2;
}


SWIGEXPORT jboolean JNICALL Java_open62Wrap_open62541JNI_UA_1DataValue_1hasSourcePicoseconds_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jboolean jresult = 0 ;
  UA_DataValue *arg1 = (UA_DataValue *) 0 ;
  UA_Boolean result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(UA_DataValue **)&jarg1; 
  result = (UA_Boolean) ((arg1)->hasSourcePicoseconds);
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_open62Wrap_open62541JNI_UA_1DataValue_1hasServerPicoseconds_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jboolean jarg2) {
  UA_DataValue *arg1 = (UA_DataValue *) 0 ;
  UA_Boolean arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(UA_DataValue **)&jarg1; 
  arg2 = jarg2 ? true : false; 
  if (arg1) (arg1)->hasServerPicoseconds = arg2;
}


SWIGEXPORT jboolean JNICALL Java_open62Wrap_open62541JNI_UA_1DataValue_1hasServerPicoseconds_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jboolean jresult = 0 ;
  UA_DataValue *arg1 = (UA_DataValue *) 0 ;
  UA_Boolean result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(UA_DataValue **)&jarg1; 
  result = (UA_Boolean) ((arg1)->hasServerPicoseconds);
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_open62Wrap_open62541JNI_new_1UA_1DataValue(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  UA_DataValue *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (UA_DataValue *)new UA_DataValue();
  *(UA_DataValue **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_open62Wrap_open62541JNI_delete_1UA_1DataValue(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  UA_DataValue *arg1 = (UA_DataValue *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(UA_DataValue **)&jarg1; 
  delete arg1;
}


SWIGEXPORT void JNICALL Java_open62Wrap_open62541JNI_swig_1module_1init(JNIEnv *jenv, jclass jcls) {
  int i;
  
  static struct {
    const char *method;
    const char *signature;
  } methods[3] = {
    {
      "SwigDirector_ServerAPIBase_monitored_itemChanged", "(Lopen62Wrap/ServerAPIBase;JI)V" 
    },
    {
      "SwigDirector_ClientAPIBase_monitored_itemChanged", "(Lopen62Wrap/ClientAPIBase;JI)V" 
    },
    {
      "SwigDirector_ClientAPIBase_clientConnected", "(Lopen62Wrap/ClientAPIBase;JJLjava/lang/String;)V" 
    }
  };
  Swig::jclass_open62541JNI = (jclass) jenv->NewGlobalRef(jcls);
  if (!Swig::jclass_open62541JNI) return;
  for (i = 0; i < (int) (sizeof(methods)/sizeof(methods[0])); ++i) {
    Swig::director_method_ids[i] = jenv->GetStaticMethodID(jcls, methods[i].method, methods[i].signature);
    if (!Swig::director_method_ids[i]) return;
  }
}


#ifdef __cplusplus
}
#endif

